### ISSUE TITLE
Yo, I haven't a clue where Java is on this system. Crashing...

### ISSUE THREAD

**Issue by Andis59** [kaby76/Antlr4BuildTasks#1]
I have just created my first program using Antlr4. I have installed OpenJDK 12.0.2, and downloaded antlr-4.7.2-complete.jar. I have also installed AntlrVSIX, version 3.0.2 and Antlr4BuildTasks, version 1.0.7 (from NuGet).

I have tested my grammar from the command line and it works like designed.

I then created a new project using the AntlrFAProject template. Removed all .cs files and the grammar and added my grammar (simple.g4)

When I now re build the project I get this error directly:
Yo, I haven't a clue where Java is on this system. Crashing...

I have added JAVA_HOME and Antlr4ToolPath to Environment Variables. I have also added the path to the bin directory to the PATH variable.

I then tried to add JAVA_HOME and Antlr4ToolPath to .csproj, but ....

Is OpenJDK the problem or have I missed something?

**Comment by kaby76** [comment]
Hi Andis59,

Please verify that you have these variables set up as expected. Try
"$JAVA_HOME/bin/java.exe" -jar "$Antlr4ToolPath"
from a Git Bash or
"%JAVA_HOME%\bin\java.exe" -jar "%Antlr4ToolPath%"
from a Cmd.exe.
That should execute the Antlr tool and print out the options expected for the command. I don't think PATH needs to be changed. If it doesn't work, adjust JAVA_HOME and Antlr4ToolPath. JAVA_HOME should be the full path of the JDK; Antlr4ToolPath should be the full path of the Antlr tool jar file. If you look at the generated .csproj file for the Antlr Console program generated, you should see what it defaults if they aren't set.

If that works, generate a new Antlr Console project using the AntlrFAConsole template, build it, and run.

If that all works, go back to your project with your grammar, and make sure the .csproj file generated by AntlrVSIX in VS2019 is changed for your grammar file. By default, the .csproj file needs to have an Antlr item like <Antlr4 Include="Java9.g4"/> for your grammar. You can change the project in VS by adding your .g4 files to your project under the Solution Manager, then set the "Build Action" to "ANTLR 4 Grammar" under Properties for the .g4 file. Or you can edit the .csproj file to reference your grammar file.

Let me know how it goes.

Ken

**Comment by Andis59** [comment]
Hello Ken,

As usual it was an error between the chair and the keyboard!
I had set JAVA_HOME to the bin directory...

When I set it to the HOME directory it found java!
Thanks!!

// Anders
