### ISSUE TITLE
Generated Program.cs gives CS1503 at line 17

### ISSUE THREAD

**Issue by ejjeamore** [kaby76/Antlr4BuildTasks#16]
changed single quote
if (args[i].StartsWith('-')) continue;
to
if (args[i].StartsWith("-")) continue;

it passed ok.

**Comment by kaby76** [comment]
You are right, it doesn't compile for older targets, e.g., `<TargetFramework>net471</TargetFramework>`, `<TargetFramework>netstandard2.0</TargetFramework>`. I'll change it for v8.10, which will have a smarter tool for templating.
