### ISSUE TITLE
The "GetJava" task failed unexpectedly

### ISSUE THREAD

**Issue by stuartharper01** [kaby76/Antlr4BuildTasks#21]
Hello

I have created a .Net Core 3.1 project in Visual Studio 2019 (16.5.1) with the following NuGet packages:
Antlr4.Runtime.Standard (4.9.2)
Antlr4BuildTasks (8.14.0)

I have then created a grammar file and amended the csproj file like this:
```
<ItemGroup>
   <Antlr4 Include="QueryLanguage.g4" />
</ItemGroup>
```
When I try to compile the project I get the following Error:
The "GetJava" task failed unexpectedly

Can you help please?
Thanks

**Comment by kaby76** [comment]
Hi, Upgrade from Antlr4BuildTasks version 8.14.0 to 8.16.0. Then try setting the build to verbosity to diagnostic (`dotnet -v diag` or `msbuild -verbosity:diag`) and post the output. --Ken

**Comment by stuartharper01** [comment]
Thanks for getting back to me - output is below.
It looks like this path is the problem "obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe"
On my machine, there is no folder after this "obj\Debug\netcoreapp3.1\Java\jre"

1>Target "Antlr4GetBuildDeps" in file "C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\Antlr4BuildTasks.targets":
1>  Task "Message"
1>    Task Parameter:Text=Tasks for Antlr in 'C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\..\lib\netstandard2.0\Antlr4BuildTasks.dll'
1>    Tasks for Antlr in 'C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\..\lib\netstandard2.0\Antlr4BuildTasks.dll'
1>  Done executing task "Message".
1>  Using "GetJava" task from assembly "C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\..\lib\netstandard2.0\Antlr4BuildTasks.dll".
1>  Task "GetJava"
1>    Task Parameter:IntermediateOutputPath=obj\Debug\netcoreapp3.1\
1>    Output Item(s): UsingJavaExec=obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe
1>  Done executing task "GetJava".
1>  Task "Message"
1>    Task Parameter:Text=The output from GetJava task is 'obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe'
1>    The output from GetJava task is 'obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe'
1>  Done executing task "Message".
1>  Using "GetAntlrJar" task from assembly "C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\..\lib\netstandard2.0\Antlr4BuildTasks.dll".
1>  Task "GetAntlrJar"
1>    Task Parameter:
1>        PackageReference=
1>            Antlr4.Runtime.Standard
1>                    Version=4.9.2
1>            Antlr4BuildTasks
1>                    Version=8.16.0
1>    Task Parameter:IntermediateOutputPath=obj\Debug\netcoreapp3.1\
1>    Task Parameter:AntlrProbePath=
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.9.2/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.9.1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.9/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.8-1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.8/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.7.2/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.7.1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.7/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.6/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.5.3/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.5.2-1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.5.2/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.5.1-1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.5.1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.5/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.3/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.2.2/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.2.1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.2/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.1/;
1>          https://repo1.maven.org/maven2/org/antlr/antlr4/4.0/
1>    Probing file:///C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\antlr-4.9.2-complete.jar
1>    Local path C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\antlr-4.9.2-complete.jar
1>    got it.
1>    Output Item(s): UsingToolPath=C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\antlr-4.9.2-complete.jar
1>  Done executing task "GetAntlrJar".
1>  Task "Message"
1>    Task Parameter:Text=The output from GetAntlrJar task is 'C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\antlr-4.9.2-complete.jar'
1>    The output from GetAntlrJar task is 'C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\antlr-4.9.2-complete.jar'
1>  Done executing task "Message".
1>Done building target "Antlr4GetBuildDeps" in project "ConsoleApp1.csproj".
1>Target "Antlr4CompileReadGeneratedFileList" skipped, due to false condition; (Exists($(Antlr4ToCompileListFile))) was evaluated as (Exists(obj\Debug\netcoreapp3.1\ConsoleApp1.csproj.AntlrToCompileList.txt)).
1>Target "Antlr4Compile" in file "C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\Antlr4BuildTasks.targets":
1>  Building target "Antlr4Compile" completely.
1>  Output file "obj\Debug\netcoreapp3.1\ConsoleApp1.csproj.AntlrToCompileList.txt" does not exist.
1>  Task "Message"
1>    Task Parameter:Text=Running the Java Antlr Tool over the grammar files 'QueryLanguage.g4'.
1>    Running the Java Antlr Tool over the grammar files 'QueryLanguage.g4'.
1>  Done executing task "Message".
1>  Using "RunAntlrTool" task from assembly "C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\..\lib\netstandard2.0\Antlr4BuildTasks.dll".
1>  Task "RunAntlrTool"
1>    Task Parameter:BuildTaskPath=C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\..\lib\netstandard2.0
1>    Task Parameter:DOptions=language=CSharp
1>    Task Parameter:Encoding=UTF-8
1>    Task Parameter:Error=False
1>    Task Parameter:ForceAtn=False
1>    Task Parameter:GAtn=False
1>    Task Parameter:IntermediateOutputPath=obj\Debug\netcoreapp3.1\
1>    Task Parameter:JavaExec=obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe
1>    Task Parameter:Listener=True
1>    Task Parameter:
1>        SourceCodeFiles=
1>            C:\Code\Test2\ConsoleApp1\ConsoleApp1\QueryLanguage.g4
1>                    AntOutDir=
1>                    CopyToOutputDirectory=Never
1>                    DOptions=language=CSharp
1>                    Encoding=UTF-8
1>                    Error=false
1>                    ForceAtn=false
1>                    GAtn=false
1>                    Generator=MSBuild:Compile
1>                    IntermediateOutputPath=obj\Debug\netcoreapp3.1\
1>                    LibPath=
1>                    Listener=true
1>                    Package=
1>                    Visitor=true
1>    Task Parameter:TargetFrameworkVersion=v3.1
1>    Task Parameter:ToolPath=C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\antlr-4.9.2-complete.jar
1>    Task Parameter:Visitor=True
1>    Starting Antlr4 Build Tasks. ToolPath is "C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\antlr-4.9.2-complete.jar"
1>    Note AntOutDir is empty. Placing generated files in IntermediateOutputPath obj\Debug\netcoreapp3.1\
1>    JavaExec is "obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe"
1>    C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\Antlr4BuildTasks.targets(196,3): error ANT02: Cannot find Java executable, currently set to 'obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe'   at Antlr4.Build.Tasks.RunAntlrTool.Execute()
1>  Done executing task "RunAntlrTool" -- FAILED.
1>Done building target "Antlr4Compile" in project "ConsoleApp1.csproj" -- FAILED.
1>
1>Done building project "ConsoleApp1.csproj" -- FAILED.
1>
1>Project Performance Summary:
1>       64 ms  C:\Code\Test2\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj   1 calls
1>
1>Target Performance Summary:
1>        0 ms  _CollectTargetFrameworkForTelemetry        1 calls
1>        0 ms  CleanXsdCodeGen                            1 calls
1>        0 ms  Clean                                      1 calls
1>        0 ms  AfterClean                                 1 calls
1>        0 ms  CleanReferencedProjects                    1 calls
1>        0 ms  PrepareProjectReferences                   1 calls
1>        0 ms  _SplitProjectReferencesByFileExistence     1 calls
1>        0 ms  ResolvePackageDependenciesForBuild         1 calls
1>        0 ms  IncludeTransitiveProjectReferences         1 calls
1>        0 ms  ResolveLockFileCopyLocalFiles              1 calls
1>        0 ms  ResolveLockFileAnalyzers                   1 calls
1>        0 ms  _ComputePackageReferencePublish            1 calls
1>        0 ms  _DefaultMicrosoftNETPlatformLibrary        1 calls
1>        0 ms  BeforeClean                                1 calls
1>        0 ms  BeforeRebuild                              1 calls
1>        0 ms  _SdkBeforeRebuild                          1 calls
1>        0 ms  _SdkBeforeClean                            1 calls
1>        0 ms  _CheckForUnsupportedNETCoreVersion         1 calls
1>        0 ms  EnableIntermediateOutputPathMismatchWarning   1 calls
1>        0 ms  _CheckForUnsupportedCppNETCoreVersion      1 calls
1>        0 ms  CollectPackageReferences                   1 calls
1>        0 ms  _CheckForLanguageAndFeatureCombinationSupport   1 calls
1>        0 ms  _CheckForObsoleteDotNetCliToolReferences   1 calls
1>        0 ms  _GetProjectJsonPath                        1 calls
1>        0 ms  UpdateAspNetToFrameworkReference           1 calls
1>        1 ms  ApplyImplicitVersions                      1 calls
1>        1 ms  ResolveLockFileReferences                  1 calls
1>        1 ms  _GetProjectReferenceTargetFrameworkProperties   1 calls
1>        1 ms  AssignProjectConfiguration                 1 calls
1>        1 ms  CheckForImplicitPackageReferenceOverrides   1 calls
1>        1 ms  CleanPublishFolder                         1 calls
1>        2 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
1>        2 ms  Antlr4GetBuildDeps                         1 calls
1>        2 ms  CheckForDuplicateItems                     1 calls
1>        3 ms  Antlr4Compile                              1 calls
1>        3 ms  _GetRestoreProjectStyle                    1 calls
1>        3 ms  CoreClean                                  1 calls
1>        4 ms  ProcessFrameworkReferences                 1 calls
1>        4 ms  CustomBeforeClean                          1 calls
1>        5 ms  _CheckForUnsupportedAppHostUsage           1 calls
1>       19 ms  ResolvePackageAssets                       1 calls
1>
1>Task Performance Summary:
1>        0 ms  Telemetry                                  1 calls
1>        0 ms  CheckIfPackageReferenceShouldBeFrameworkReference   2 calls
1>        0 ms  CheckForDuplicateFrameworkReferences       1 calls
1>        0 ms  GetJava                                    1 calls
1>        0 ms  ReadLinesFromFile                          2 calls
1>        0 ms  FindUnderPath                              2 calls
1>        0 ms  RemoveDuplicates                           1 calls
1>        0 ms  MakeDir                                    1 calls
1>        1 ms  WriteLinesToFile                           1 calls
1>        1 ms  ApplyImplicitVersions                      1 calls
1>        1 ms  JoinItems                                  1 calls
1>        1 ms  GetAntlrJar                                1 calls
1>        1 ms  MSBuild                                    1 calls
1>        1 ms  AssignProjectConfiguration                 1 calls
1>        1 ms  ResolveAppHosts                            1 calls
1>        1 ms  CheckForImplicitPackageReferenceOverrides   1 calls
1>        2 ms  RunAntlrTool                               1 calls
1>        2 ms  ProcessFrameworkReferences                 1 calls
1>        2 ms  Delete                                     6 calls
1>        2 ms  CheckForDuplicateItems                     3 calls
1>        3 ms  GetRestoreProjectStyleTask                 1 calls
1>        4 ms  Message                                   11 calls
1>       17 ms  ResolvePackageAssets                       1 calls
1>
1>Build FAILED.
1>
1>C:\Users\BADE\.nuget\packages\antlr4buildtasks\8.16.0\build\Antlr4BuildTasks.targets(196,3): error ANT02: Cannot find Java executable, currently set to 'obj\Debug\netcoreapp3.1\Java\jre\bin\java.exe'   at Antlr4.Build.Tasks.RunAntlrTool.Execute()
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.06
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by kaby76** [comment]
Hi, I was wondering, did you edit the output file? Some of the paths in the output look terrible. The standard path for the .nuget directory for a User "whatever-user-name" is "c:\users\whatever-user-name-you-are\.nuget". You have "C:\Users\BADE.nuget". That's missing the '\' separator character between the user name and .nuget. This is a non-standard place from where the Nuget tool would place packages. Looking further at the path, I see "\build..\lib" which is also a bad path change directory. I edit paths in the tool, but I don't think I remove critical backslashes, and the code that appends ".." has path separators explicitly added. These paths have to be perfect, or yes, nothing will work. Thanks for the info. --Ken

**Comment by kaby76** [comment]
Ok, I see. I edited your post here in Github. You have to indent by 4 or use a tab, otherwise Github interprets everything as Markdown.

**Comment by stuartharper01** [comment]
Hello Ken
I think I've found the problem... By doing a clean install of 8.16.0 it now works.
I think the problem was in unzipping the jre.zip.
Thanks for your help.
I don't think this is really an issue with your tool, so shall I try to delete this issue?

Thanks for creating such a good tool by the way!

**Comment by kaby76** [comment]
Glad you fixed the issue. I was going to suggest deleting the .nuget/, bin/, and obj/ directories, and start over with a "restore". I'll close the issue at this point. Thanks-Ken
