### ISSUE TITLE
Build Errors Since > 8.16.0

### ISSUE THREAD

**Issue by martin-shields-sage** [kaby76/Antlr4BuildTasks#24]
Hi, we have encountered an issue since trying to update this package on our repo from 8.16.0 to 8.17.0/8.18.0/8.20.0. The error we get is:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GetAntlrJar" task failed unexpectedly.
System.Exception: Antlr4BuildTasks is going to return an empty UsingToolPath, but it should never do that.
   at Antlr4.Build.Tasks.GetAntlrJar.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	DirectoryService.Core.ODataFilterParser	C:\Users\**\.nuget\packages\antlr4buildtasks\8.20.0\build\Antlr4BuildTasks.targets	170	

You don't happen to know why this would happen?

**Comment by kaby76** [comment]
I've been working on the error messaging in the build tasks lately, and it should be giving better messaging as to why it's failing. But, it looks like it needs more work.

GetAntlrJar is trying to find the Antlr4 tool jar file, and can't find it. It uses the .jar file to generate a parser via Java ("java -jar _full-path-to-jar_ *.g4"). While it contains a copy of the latest jar, 4.9.3, in the Nuget package, if you want something other than 4.9.3, it'll start probing for the file, then try to download the file. It looks it's failing to do any of that.

Try turning on "diagnostics" in the build and let me know what the GetAntlrJar task is outputting.

**Comment by kaby76** [comment]
I believe I found the problem--embedded new lines in paths causing the logic to fail. Will upload version 8.21 soon.

**Comment by martin-shields-sage** [comment]
Ok will do. I am in the middle of something at the moment but will check either later today or tomorrow if that is ok

**Comment by martin-shields-sage** [comment]
Thanks for looking into this so swiftly as well

**Comment by martin-shields-sage** [comment]
Looks like this is resolved, thank you very much
