### ISSUE TITLE
Build failure using Antlr4.Runtime.Standard 4.10.1 but not 4.9.3

### ISSUE THREAD

**Issue by El-Gor-do** [kaby76/Antlr4BuildTasks#31]
I don't know if this bug is in Antlr4.Runtime.Standard or Antlr4BuildTasks. If this is the wrong repository for the bug then I can raise it in the appropriate repository instead.

Create a class library project containing just the 2 files below:

**ClassLibrary1.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.9.3" />
    <PackageReference Include="Antlr4BuildTasks" Version="10.3.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Include="HelloWorldGrammar.g4" />
  </ItemGroup>
</Project>
```

**HelloWorldGrammar.g4**
```
grammar HelloWorldGrammar;
r   : 'hello' ID;
ID  : [a-z]+ ;
WS  : [ \t\r\n]+ -> skip ;
```

Run `dotnet build` and you will get a bunch of warnings about not needing CLSCompliant attribute but otherwise the build is successful.

Now change Antlr4.Runtime.Standard version to either 4.10.0 or 4.10.1, run `dotnet build` and get the following build errors:
```
...\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarParser.cs(67,25): error CS1715: 'HelloWorldGrammarParser.SerializedAtn': type must be 'int[]' to match overridden member 'Recognizer<IToken, ParserATNSimulator>.SerializedAtn' [...\ClassLibrary1\ClassLibrary1.csproj]
...\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarLexer.cs(84,25): error CS1715: 'HelloWorldGrammarLexer.SerializedAtn': type must be 'int[]' to match overridden member 'Recognizer<int, LexerATNSimulator>.SerializedAtn' [...\ClassLibrary1\ClassLibrary1.csproj]
```

In both _HelloWorldGrammarParser.cs_ and _HelloWorldGrammarLexer.cs_ the errors are in `public override string SerializedAtn { get { return new string(_serializedATN); } }` where `SerializedAtn` should return `int[]` rather than `string` type.

**Comment by kaby76** [comment]
For the warnings, I don't have control over the Antlr4 runtime. So, this is why I suggested adding these lines to the .csproj.
```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>3021;1701;1702</NoWarn>
</PropertyGroup>
```
Yes, when you change the Antlr4.Runtime.Standard version referenced, it's not rerunning the Antlr tool to regenerate new parser and lexer, but the compiler is trying to resolve the older generated code with the newer Antlr4.Runtime.Standard library. There should be a dependency on the generated code with the .csproj, but it's not there. Antlr4BuildTasks downloads the Antlr4 jar file from Maven Central corresponding to what you listed in the .csproj. Thanks for the note.

In the meanwhile, just remove the obj/ directory, and rebuild.

**Comment by El-Gor-do** [comment]
Thanks, for this repro I wasn't bothered by the build warnings so I just ignored them. After referencing Antlr4.Runtime.Standard 4.10.1, deleting the obj directory and building again, the build error is now
```
...\.nuget\packages\antlr4buildtasks\10.3.0\build\Antlr4BuildTasks.targets(131,3): error ANT02: The Antlr4 tool failed. [...\ClassLibrary1\ClassLibrary1.csproj]
```

**Comment by kaby76** [comment]
Right. That's another bug. That's because you used "4.10.0" over "4.10". I tried to write code to test for "4.10" if you pass "4.10.0" instead, but apparently that code is broken again. Just use "4.10", remove the obj/ directory, then try again and it should work. Thanks.

**Comment by El-Gor-do** [comment]
After changing the pacakge reference to `<PackageReference Include="Antlr4.Runtime.Standard" Version="4.10" />`, deleting bin and obj directories and rebuilding, I am still getting the same `error ANT02: The Antlr4 tool failed. [...\ClassLibrary1\ClassLibrary1.csproj]`

**Comment by kaby76** [comment]
I'll need more details; I can't reproduce.

```
$ cat Test.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.10" />
    <PackageReference Include="Antlr4BuildTasks" Version="10.3.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Include="HelloWorldGrammar.g4" />
  </ItemGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>3021;1701;1702</NoWarn>
</PropertyGroup>
</Project>

$ cat HelloWorldGrammar.g4
grammar HelloWorldGrammar;
r   : 'hello' ID;
ID  : [a-z]+ ;
WS  : [ \t\r\n]+ -> skip ;

$ ls
bin/  HelloWorldGrammar.g4  obj/  Test.csproj

$ rm -rf bin obj

$ dotnet --version
6.0.202

$ dotnet build
Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\msys64\home\Kenne\stuff\Test.csproj (in 292 ms).
  Test -> C:\msys64\home\Kenne\stuff\bin\Debug\net6.0\Test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.20

```

**Comment by El-Gor-do** [comment]
I'm running on Windows 10 rather than Linux. My csproj and HelloWorldGrammar.g4 are identical to yours.

`dotnet version` is the same, 6.0.202.

```
dotnet --list-sdks
3.1.418 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]
5.0.213 [C:\Program Files\dotnet\sdk]
5.0.300 [C:\Program Files\dotnet\sdk]
5.0.400 [C:\Program Files\dotnet\sdk]
5.0.403 [C:\Program Files\dotnet\sdk]
5.0.407 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.102 [C:\Program Files\dotnet\sdk]
6.0.104 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
6.0.202 [C:\Program Files\dotnet\sdk]
```

My `dotnet build` output is
```
Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\ClassLibrary1.csproj (in 143 ms).
C:\Users\El-Gor-do\.nuget\packages\antlr4buildtasks\10.3.0\build\Antlr4BuildTasks.targets(131,3): error ANT02: The Antlr4 tool failed. [D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\ClassLibrary1.csproj]

Build FAILED.

C:\Users\El-Gor-do\.nuget\packages\antlr4buildtasks\10.3.0\build\Antlr4BuildTasks.targets(131,3): error ANT02: The Antlr4 tool failed. [D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\ClassLibrary1.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.75
```

My Java runtime was installed from https://community.chocolatey.org/packages/jre8 using the command line `choco install jre8`

**Comment by kaby76** [comment]
My system is Windows 11 with Msys64.

Please try `dotnet build -v diag` with stderr and stdout redirected to a .txt, then attach it to a comment?

**Comment by El-Gor-do** [comment]
Here is my MSBuild log from `dotnet build /flp:v=diag`
[msbuild.log](https://github.com/kaby76/Antlr4BuildTasks/files/8645467/msbuild.log)

**Comment by kaby76** [comment]
```
Executing command: "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -cp C:/Users/El-Gor-do/.nuget/packages/antlr4buildtasks/10.3.0/build/antlr4-4.10-complete.jar org.antlr.v4.Tool -depend -o D:/dev/bugs/Antlr410BuildFailure/ClassLibrary1/obj/Debug/net6.0/ -encoding UTF-8 -listener -visitor -Dlanguage=CSharp D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4 (TaskId:52)
Error: A JNI error has occurred, please check your installation and try again (TaskId:52)
```
Seems likely that the Java you installed is incompatible with the .jar. Try executing the java.exe command verbatim and see if it's your Java. Note, Antlr4BuildTasks includes a JRE for Windows but it uses anything else on your"$PATH" before defaulting to that.

**Comment by El-Gor-do** [comment]
The output of `"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -showversion`
```
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)
```

The output of `"C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -cp C:/Users/El-Gor-do/.nuget/packages/antlr4buildtasks/10.3.0/build/antlr4-4.10-complete.jar org.antlr.v4.Tool -depend -o D:/dev/bugs/Antlr410BuildFailure/ClassLibrary1/obj/Debug/net6.0/ -encoding UTF-8 -listener -visitor -Dlanguage=CSharp D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4`
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/antlr/v4/Tool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

JRE8 is probably the problem. Not being a Java person, I misunderstood the guidance from https://github.com/antlr/antlr4/releases/tag/4.10 and thought I only needed to have JRE8 installed but on reading it again it looks like I need JRE11.

**Comment by kaby76** [comment]
I saw an issue somewhere about ising version 8 of Java, but I hadn't found it yet. I recommend you unpack a version of Java 11, remove Java 8, and put the bin directory on your PATH. You may want to typ in the java -jar command from time to time.

**Comment by El-Gor-do** [comment]
After installing JRE11 from https://community.chocolatey.org/packages/openjdk11jre/ I was able to run `"C:\Program Files\OpenJDK\openjdk-11.0.15_10-jre\bin\java.exe" -cp C:/Users/El-Gor-do/.nuget/packages/antlr4buildtasks/10.3.0/build/antlr4-4.10-complete.jar org.antlr.v4.Tool -depend -o D:/dev/bugs/Antlr410BuildFailure/ClassLibrary1/obj/Debug/net6.0/ -encoding UTF-8 -listener -visitor -Dlanguage=CSharp D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4` and got this output
```
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarParser.cs : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammar.tokens : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarLexer.cs : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarLexer.tokens : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarListener.cs : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarBaseListener.cs : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarVisitor.cs : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\obj\Debug\net6.0\HelloWorldGrammarBaseVisitor.cs : D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\HelloWorldGrammar.g4
```

But my PATH environment variable has `C:\Program Files (x86)\Common Files\Oracle\Java\javapath` before `C:\Program Files\OpenJDK\openjdk-11.0.15_10-jre\bin` so `dotnet build` still calls JRE8. I will uninstall JRE8 and see what happens.

**Comment by El-Gor-do** [comment]
After uninstalling JRE8, `dotnet build` finally succeeds even if I change the Antlr4.Runtime.Standard version from `4.10` back to `4.10.1`

**Comment by kaby76** [comment]
Good. Thanks for the note. There are a few things to fix.

**Comment by El-Gor-do** [comment]
Thanks for your help resolving this. For anyone reading this in future, the TLDR when upgrading from Antlr4.Runtime.Standard 4.9.x to 4.10.x is
* delete the project's existing _obj_ directory
* ensure that JRE11 is installed (I installed it using Chocolatey https://community.chocolatey.org/packages/openjdk11jre/)
* if JRE8 and JRE11 are both installed then ensure that the _PATH_ environment variable has JRE11's directory before JRE8's directory
