### ISSUE TITLE
Cannot use both Antlr4.Runtime and Antlr4.Runtime.Standard in same project

### ISSUE THREAD

**Issue by danieln-cx** [kaby76/Antlr4BuildTasks#32]
I was using `Antlr4BuildTasks 8.17.0` with `Antlr4.Runtime.Standard 4.9.3` in a project that also referenced the "old" `Antlr4.Runtime 4.6.6` and everything worked fine. I was able to maintain both nugets without namespace conflicts in the code by using an alias with the later:
```
<PackageReference Include="Antlr4.Runtime" Version="4.6.6">
   <Aliases>Antlr4Legacy</Aliases>
   <PrivateAssets>contentfiles;analyzers;build;compile</PrivateAssets>
</PackageReference>
```

I wont get into the reasons why I have such setup, but it used to work. 
When trying to update to `Antlr4.Runtime.Standard 4.10.1` and `Antlr4BuildTasks 10.3.0` this stopped working and I have the following message:

> You are referencing Antlr4.Runtime in your .csproj file. This build tool can only reference the NET Standard library https://www.nuget.org/packages/Antlr4.Runtime.Standard/. You can only use either the 'official' Antlr4 or the 'tunnelvision' fork, but not both. You have to choose one.

Since there is a way for this to work, can you remove such error? Or provide a way to make it still work?

Thanks!

**Comment by kaby76** [comment]
Hi, I updated the code to offer an option in the csproj/UI to bypass the check for Antlr4.Runtime. To bypass the check, set `<AllowAntlr4cs>true</AllowAntlr4cs>` in the csproj or use the VSIDE to set the option through the UI. You will still need to do the aliasing in the csproj you show above. The change is In version 10.4 which I just pushed to nuget.org. --Ken

**Comment by danieln-cx** [comment]
That was amazingly fast @kaby76! Thank you very much 😀
