### ISSUE TITLE
Project rebuild fails but build succeeds using Antlr4BuildTasks 10.5.0

### ISSUE THREAD

**Issue by El-Gor-do** [kaby76/Antlr4BuildTasks#36]
I am using .Net SDK 6.0.300 on Windows 10. After upgrading Antlr4BuildTasks to 10.5.0, my projects fail to rebuild where previously 10.4.0 was successful. To reproduce, create a project with the following 2 files:

**ClassLibrary1.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <NoWarn>3021</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.10.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="10.4.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Antlr4 Include="HelloWorldGrammar.g4" />
  </ItemGroup>
</Project>
```

**HelloWorldGrammar.g4**
```
grammar HelloWorldGrammar;
r   : 'hello' ID;
ID  : [a-z]+ ;
WS  : [ \t\r\n]+ -> skip ;
```

Cleaning and building the project is successful:
```
dotnet clean
dotnet build
```

Cleaning and rebuilding the project is also successful:
```
dotnet clean
dotnet build --no-incremental
```

Now update Antlr4BuildTasks package reference from 10.4.0 to 10.5.0. Cleaning and building will still be succesful but `dotnet build --no-incremental` fails with
```
C:\Users\El-Gor-do\.nuget\packages\antlr4buildtasks\10.5.0\build\Antlr4BuildTasks.targets(132,3): error ANT02: You are using <Reference> for Antlr4.Runtime.Standard in your .csproj file. You can only use <PackageReference> for the package, never a link to the dll.   at Antlr4.Build.Tasks.RunAntlrTool.SetupAntlrToolJar() [D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\ClassLibrary1.csproj]
C:\Users\El-Gor-do\.nuget\packages\antlr4buildtasks\10.5.0\build\Antlr4BuildTasks.targets(132,3): error ANT02:    at Antlr4.Build.Tasks.RunAntlrTool.Execute() [D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\ClassLibrary1.csproj]
C:\Users\El-Gor-do\.nuget\packages\antlr4buildtasks\10.5.0\build\Antlr4BuildTasks.targets(132,3): error ANT02: The Antlr4 tool failed. [D:\dev\bugs\Antlr410BuildFailure\ClassLibrary1\ClassLibrary1.csproj]
```

**Comment by kaby76** [comment]
I need to see the .csproj that causes the failure, not the one that works. That .csproj uses Antlr4BuildTasks version 10.4, not 10.5.

**Comment by kaby76** [comment]
Sorry, it fails in both 10.4 and 10.5. But, it's fixed in 10.6, which I'll release today. The entire fetching of the Java JRE had to be redone to align with Parr's new tool https://github.com/parrt/antlr4/blob/new-antlr-tool/scripts/antlr4/antlr4_tool_runner.py .

**Comment by kaby76** [comment]
Thanks for the note, and sorry for my rambling. Version 10.6, which I just released, should work. I removed the unnecessary checks.

**Comment by El-Gor-do** [comment]
Thanks for the quick fix. I can confirm that both `dotnet build` and `dotnet build --no-incremental` both run successfully with 10.6.0.
