### ISSUE TITLE
How to determine interface for the result of a build?

### ISSUE THREAD

**Issue by asfarley** [kaby76/Antlr4BuildTasks#37]
I've followed the tutorials and successfully built a lexer/parser using the Readme guide, in VS2022. 

I have basically only done the absolute minimum to get the project building:
 * Create a grammar file
 *  Add an empty .CS file
 * Add appropriate nuget packages (Antlr4.Runtime.Standard, Antlr4BuildTasks)
 * Build project
 * Generated files appear

Is there any guidance on how to use the generated output? For example, I see some classes have been created:

LanguageLexer
LanguageParser

It appears that LanguageLexer accepts an input of Anltr4.Runtime.ICharStream; is there a function to convert an input file to this type?

**Comment by asfarley** [comment]
Nevermind, I found an answer on the main Antlr4 repo.

**Comment by kaby76** [comment]
Now that you have the build environment working, I would recommend that you try the Antlr4Templates package I wrote to create a basic Antlr parser with driver e.g. `dotnet new csharp-combine`. You can then open the project in VS2022, build, and single step through the program to see how it works. That should help start to answer some of your questions on how to use Antlr. Let me know how it goes.

**Comment by asfarley** [comment]
Thank you, looks like Antlr4Templates had exactly what I needed.

**Comment by asfarley** [comment]
One thought - while the example does show how to set up an ErrorListener, I would also be interested in seeing examples of setting up custom listeners and visitors. 

The Antlr4 documentation does provide a very loose example of how to do this, but it's written in fragments as opposed to a single compile-able project. Having this included in the templates could be helpful to clarify any ambiguities.

**Comment by kaby76** [comment]
I agree. There should be examples of listeners, visitors, recovery, error messages, etc.
