### ISSUE TITLE
"Build" triggered unexpectedly

### ISSUE THREAD

**Issue by asfarley** [kaby76/Antlr4BuildTasks#38]
Using Visual Studio 2022 17.2.3

I'm noticing some unusual behavior. When I set the path for generated files in File Properties (for my grammar), it appears that the files are generated immediately, as if modifying this field is a trigger for the build itself. 

Is this intentional? 

Then, if I "Build Solution" manually, I get 97 error messages indicating duplicate definitions:
![image](https://user-images.githubusercontent.com/1622578/171702614-d41a1d1c-dc6d-45da-9ee9-c6d842091d89.png)

Here is a repository to reproduce this issue:
https://github.com/asfarley/antlrbuilddemo

Please let me know if I've done something incorrectly or if you need more information.

**Comment by kaby76** [comment]
Sorry, github automatically closes when I commit a change in the code when I say "fixed" and some issue number. In any case, the whole thing with "./Generated" is now fixed in version 10.7.
