### ISSUE TITLE
Error MSB3231: Directory %documents%/.jre cannot be deleted

### ISSUE THREAD

**Issue by burdoto** [kaby76/Antlr4BuildTasks#51]
Hi
When trying to build a project that contains:
- a desktop app that uses AntlrBuildTasks to compile antlr grammar
- a xamarin android app that depends on this desktop app

I get an error MSB3231 regarding the process cannot access/delete the JRE zip file.
Unfortunately I only have the german error notification:
```
0>C:\Users\burdo\.nuget\packages\antlr4buildtasks\11.5.0\build\Antlr4BuildTasks.targets(192,3): Error MSB3231 : Das Verzeichnis "C:/Users/burdo/.jre/" kann nicht entfernt werden. Der Prozess kann nicht auf die Datei "OpenJDK11U-jre_x64_windows_hotspot_11.0.15_10.zip" zugreifen, da sie von einem anderen Prozess verwendet wird.
```

For further notice; [this is the project in question](https://github.com/comroid-git/clmath/tree/android) (the Antlr4BuildTasks plugin is currently disabled)

**Comment by burdoto** [comment]
A followup problem is that, as long as the project targets net6.0 as well as netcoreapp3.1+netstandard2.1, the output files are only ever put into the obj directory for net6.0

**Comment by kaby76** [comment]
I'm not sure I understand the project structure. The Xamarin "app" references another project, which is a "app"---also known as an .exe Windows executable? Or a "library"?

Could you perform the follow steps?
* Remove c:/Users/burdo/.rje completely. This is a directory containing files used by the package.
* At the command line, run `java -version` and indicate what, if any, version of java you have installed and on PATH.
* Edit the .csproj file for the project that contains the .g4's. Change the version for Antlr4BuildTasks to "12.0". Verify that it is `<ItemGroup><PackageReference Include="Antlr4.Runtime.Standard" Version ="4.11.1" /><PackageReference Include="Antlr4BuildTasks" Version = "12.0" PrivateAssets="all" /></ItemGroup>`. Verify you have `<PropertyGroup><TargetFrameworks>net5.0;netstandard2.1;netcoreapp3.1</TargetFrameworks></PropertyGroup>` in your .csproj. Verify you have `<ItemGroup><Antlr4 Include="your-grammar-file-name.g4"></Antlr4>`.
* In your Xamarin app, verify that it does not reference Antlr4BuildTasks. It doesn't contain the .g4's, so there's no need to run the tool.
* In the directory containing the .csproj, run `dotnet build`. What is the build result?

**Comment by burdoto** [comment]
The Xamarin app depends on the Desktop App because logic from that desktop App wants to be used for the Android app.

These are the dependencies:
Xamarin App
- Depends on Desktop App
  - Depends on Antlr4BuildTools 12
  - Depends on Antlr 4.11.1

Regarding your troubleshooting steps:
- I've tried deleting the .jre directory already, with no luck.
- Java 1.8 is available from the command line.
- I have made the adjustments, with no success. Still getting the same error.
- The Xamarin app itself does not implicitly depend on Antlr4BuildTasks; but it is still contained because the Desktop Appdepends on it.
- When running `dotnet build`, then I just get a bunch of "class not found" errors regarding the Antlr classes. When using Rider rebuild functionality, then I still get the above error.

Personally I think this is due to Xamarin somehow using Java during build, making it impossible for Antlr4BuildTools to redownload Java. I am kind of confused why it does download Java in the first place, since it's available from path.

**Comment by kaby76** [comment]
* You're going to have to reboot and try to delete the .jre directory immediately after rebooting. A process is locking it, or you have Admin privileges. If reboot then delete doesn't work, rename the directory, reboot, then delete the .jre directory. It really needs to go away because there's no use looking over the state of the files.
* Java 8 is NOT sufficient for Antlr4.11.1. It requires Java 11 at least. That's why it's trying to download and set up a .jre.

**Comment by burdoto** [comment]
As long as the build doesn't run, I can easily delete the .jvm directory. I just wont delete during build.
Tho I will change my path to contain a Java 11 version.

**Comment by burdoto** [comment]
Even with a Java 18 in path, the tool still gets the same error.

**Comment by kaby76** [comment]
Could you do reboot, remove `$USERPROFILE/.jre` (not `$USERPROFILE/.jvm`, which I have no idea what that is), then do a "dotnet build -v=diag" and post? I really do not understand the details here. Thanks.

**Comment by burdoto** [comment]
Of course I meant `.jre` and made a mistake.

I did all these steps, with no real success. I'm getting a very strange error now, regarding Xamarin not being available, which is wrong because it is available.
https://paste.kescher.at/?2aabd9b2b20d1a44#DvNDrfWdPAQsJWGNmcKHs4PZpXow4sg1ghQLkavMTL94
I hope it includes all information you need.

**Comment by kaby76** [comment]
I don't even see a reference to Antlr4BuildTasks in the posted `build -v=diag` output, no error messages from the package itself. I have no idea if you are actually building an Antlr4 program from that output. Thanks.

**Comment by burdoto** [comment]
My issue is that the output is VERY long. Let me try posting it as multiple things:
https://paste.kescher.at/?594b82eee1a68a57#5Nrspan9uPLYhd1iJdf67EH9tgg7L61AuCxATY1wdUo5
https://paste.kescher.at/?da84b1bb31036667#FCwwBAPy2MdsB13Dqoysi41mXiU5EceZwCtoXaybfhRQ
https://paste.kescher.at/?c43ecfe87caf9ca7#MNBk7HwzabJ2LShi1s8qgYM9wm7tYDLXmktFg2seVDW
https://paste.kescher.at/?c43ecfe87caf9ca7#MNBk7HwzabJ2LShi1s8qgYM9wm7tYDLXmktFg2seVDW
https://paste.kescher.at/?fcda938c32316412#BGDtCDf3SFDBQqhVJkR32yKKSjwdsDqFYaePHJSSXhkQ

the first three seem to contain information about the build tool

**Comment by burdoto** [comment]
My Issue was that I couldn't get all output. Printing to a .txt file seems to have helped:
[output.txt](https://github.com/kaby76/Antlr4BuildTasks/files/9997661/output.txt)

**Comment by kaby76** [comment]
The "output.txt" file doesn't say that it's running the RunAntlrTool task. Nothing can work without that, not even create a `$USERPROFILE/.jre` directory. Can I see your .csproj file that has the `<PackageReference Include="Antlr4BuildTasks"...` and has the `<Antlr4>` elements that list your .g4 files?

**Comment by burdoto** [comment]
Its this one: https://github.com/comroid-git/clmath/blob/android/clmath/clmath.csproj
In this file, the `PackageReference` is commented out, but on my machine it is not.
In Rider, I usually do a rebuild instead of a normal build.

**Comment by burdoto** [comment]
Note that this has worked, until I added the mentioned Xamarin App.

**Comment by kaby76** [comment]
OK, getting somewhere.

https://github.com/comroid-git/clmath/blob/0e88008b35acb1e3a337412e430c439464aa24dc/clmath/clmath.csproj#L26 This line is commented out. The package Antlr4BuildTasks cannot call the tool unless it is referenced. It does so by cleverly looking at the .csproj file itself for `<Antlr4>` elements. The `<Antlr4>` element that you have contains this https://github.com/comroid-git/clmath/blob/0e88008b35acb1e3a337412e430c439464aa24dc/clmath/clmath.csproj#L34 . Why is `<Generator>` set? Also, I would get rid of the `<libpath>` element to simplify the problem--you don't need to tell where to put the generated output. Simplify first, get it working, then embellish things later on.

Make sure you don't have any other .csproj that has `<PackageReference Include="Antlr4BuildTasks" ...>`.

Try uncommenting the package reference, remove the obj/ and bin/ directories, and build again with -v=diag. Thanks!

**Comment by burdoto** [comment]
Did you even read my comment? The line is not commented out on my machine. I just didn't commit & push that change.
Also, I dont know why `Generator` is set, it might have been a default value. I had no specific reason to set this.

I have now removed the `Generator` tag and also the `LibPath` tag, and now I'm getting this output: 
[output.txt](https://github.com/kaby76/Antlr4BuildTasks/files/9997741/output.txt)

**Comment by kaby76** [comment]
The build works for me.

[test.txt](https://github.com/kaby76/Antlr4BuildTasks/files/9997857/test.txt)
[output.txt](https://github.com/kaby76/Antlr4BuildTasks/files/9997859/output.txt)

What version of the NET SDK, VS2022 are you using?

**Comment by burdoto** [comment]
I have the following versions installed: ```
.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.412 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  ```

**Comment by kaby76** [comment]
```
$ dotnet --list-sdks
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.526 [C:\Program Files\dotnet\sdk]
2.1.617 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.701 [C:\Program Files\dotnet\sdk]
2.1.818 [C:\Program Files\dotnet\sdk]
2.2.103 [C:\Program Files\dotnet\sdk]
3.1.425 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]
5.0.212 [C:\Program Files\dotnet\sdk]
5.0.303 [C:\Program Files\dotnet\sdk]
5.0.406 [C:\Program Files\dotnet\sdk]
7.0.100 [C:\Program Files\dotnet\sdk]

Kenne@DESKTOP-DL44R7B MINGW64 ~/issue-51
$ which dotnet
/c/Program Files/dotnet/dotnet

Kenne@DESKTOP-DL44R7B MINGW64 ~/issue-51
$ dotnet --version
7.0.100

Kenne@DESKTOP-DL44R7B MINGW64 ~/issue-51
$
```

**Comment by kaby76** [comment]
Have you tried "dotnet build clmath.csproj" from the command line?

**Comment by burdoto** [comment]
Yes I have tried that; and it gives me the following output: 
[output.txt](https://github.com/kaby76/Antlr4BuildTasks/files/9997907/output.txt)
I'm starting to think that it may be caused by the way Rider (as opposed to VS) interacts with a project. Although then at least `dotnet build` should work.

**Comment by kaby76** [comment]
It's not Rider. And, it's not a NET6 vs NET7 issue. (github.com/antlr/grammars-v4 uses Antlr4BuildTasks on Windows, Linux, and MacOS all fine with every PR.) `dotnet build` does not seem to be working.

Have you tried a template-generated Antlr app?
```
dotnet new -i Antlr4Templates
mkdir Foo
cd Foo
dotnet new csharp-combine
dotnet run
```

**Comment by burdoto** [comment]
sorry, i don't quite know what you mean by "template-generated Antlr app".
as mentioned before, `Antlr4BuildTools` worked just fine, it does work fine on that repositories master branch; it stopped working when i added that Xamarin project.

**Comment by kaby76** [comment]
The problem occurs because you are using multiple targets and the .jre directory is marked for deletion--erroneously--in a clean or rebuild. The RunAntlrTool task outputs a list, which is [written to a text file](https://github.com/kaby76/Antlr4BuildTasks/blob/7e8c4ec83bdd0021072238316afda1282bba08c6/Antlr4BuildTasks/Antlr4BuildTasks.targets#L173). Later on, that text file is [read](https://github.com/kaby76/Antlr4BuildTasks/blob/7e8c4ec83bdd0021072238316afda1282bba08c6/Antlr4BuildTasks/Antlr4BuildTasks.targets#L194), then [tries to remove all those directories](https://github.com/kaby76/Antlr4BuildTasks/blob/7e8c4ec83bdd0021072238316afda1282bba08c6/Antlr4BuildTasks/Antlr4BuildTasks.targets#L201), but it was already removed, and the deletion is erroneously set to `TreatErrorsAsWarnings="false"`. That's where it fails.

Will fix tomorrow.

**Comment by kaby76** [comment]
Release 12.1 should fix this problem. (I tested with your repo on my machine.)

I recommend you move Math.g4 from grammar/ to clmath/. The project direcotry clmath/ contains the source for the project, and logically, Math.g4 is in the project because of the `<Antlr4>` element. The disadvantage of that is that Math.g4 is not listed in the project when edited using VS2022, and the UI to change the Antlr4 tool options will never appear. Antlr4BuildTasks does not adjust the Solution Explorer in VS2022. That is a problem I'll need to fix at some point. In the meanwhile, you'll have to manually edit the .csproj to adjust the `<Antlr4>` element if not reorganized.

**Comment by burdoto** [comment]
Thanks for the quick work on it.
Unfortunately I have to turn you down with the fact that I'm _still_ getting the same error.
Using `dotnet build` I get this output; although I'm not sure right now whether it even tries to use the Build Tool at all. I'm making a commit with my current repo's state.
[output.txt](https://github.com/kaby76/Antlr4BuildTasks/files/10003286/output.txt)

**Comment by burdoto** [comment]
I've tried to rebuild the project with VS2019 now, deleted `bin/` and `obj/` directories first, which seems to have worked perfectly fine.
At this point I would assume that the Issue has to do with how Rider interacts with projects that contain Xamarin apps (since this issue started happening in Rider since I added the Xamarin project), and I would continue further by opening an issue in the [JetBrains issue tracker](https://youtrack.jetbrains.com/), linking this issue.

**Comment by burdoto** [comment]
After deleting all `bin/` and `obj/` directories, Rider is now able to rebuild the project, including the Antlr related build targets as well.

Thanks for the quick fix!

**Comment by kaby76** [comment]
Note, I still have problems in building from scratch with VS2022. After removing bin/obj then open Vs2022 on the .sln, "Build" says 1 project failed.
```
3>Build succeeded.
3>    0 Warning(s)
3>    0 Error(s)
3>
3>Time Elapsed 00:00:00.75
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:07.869 ==========
```
A subsequent "Rebuild" says all three now succeeded. Further, I see this in the diagnostic log on the first build (immediately after removing obj/, bin/ everywhere in the solution:
```
3>    _InvalidConfigurationMessageText =     The BaseOutputPath/OutputPath property is not set for project 'clmath.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.
```
That's pretty much the only information I found that there was any error. Yet, clmath.dll exists in all three targets.
