### ISSUE TITLE
 error ANT02: Went through the complete probe list looking for an Antlr4 tool jar, but could not find anything. Fail!

### ISSUE THREAD

**Issue by SFrank1966** [kaby76/Antlr4BuildTasks#58]
I've tried to use the Antlr4BuildTasks-Nuget-Package (12.2.0) in a C#-Project with Visual Studio 2022 on Windows 10. 

Then I've got the following error messages:
error ANT02: Went through the complete probe list looking for an Antlr4 tool jar, but could not find anything. Fail!
error ANT02: Cannot find Antlr4 jar file, currently set to ''   at Antlr4.Build.Tasks.RunAntlrTool.SetupAntlrToolJar()
error ANT02:    at Antlr4.Build.Tasks.RunAntlrTool.Execute()
error ANT02: The Antlr4 tool failed.

As I understood, the package tries to download a JRE and the Antlr4 tool jar file:
Antlr4BuildTasks downloads a JRE for your OS and places it in $USERPROFILE/.jre/ on Windows and $HOME/.jre/ on Linux. The package also downloads the Antlr4 tool JAR file and places it in $USERPROFILE/.m2/ on Windows and $HOME/.m2/ on Linux.

But these folders don't exist on my machine after the build was running.

Any ideas of what could be wrong?

**Comment by SFrank1966** [comment]
Thank,you, the diagnostic output helped me going one step further.

I've tried to include the packages this way:
    <PackageReference Include="Antlr4.Runtime.Standard" Version="*" />
    <PackageReference Include="Antlr4BuildTasks" Version="*" PrivateAssets="all" />

I wanted to use the newest version of the packages. But this doesn't seem to work.
When I use the actual version number, the download is functioning.
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.11.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.2.0" PrivateAssets="all" />

Now I can build the whole project successfully.

P.S. The folder USERPROFILE/.jre is still absent, but I think there is already a JRE on my machine.

**Comment by ThreeSevenths** [comment]
Hi I'm seeing ANT02 errors again after updating to the latest version of Visual Studio 17.14.5 released on 2025-06-10.
