### ISSUE TITLE
The "SubtractList" task failed unexpectedly

### ISSUE THREAD

**Issue by emphasis87** [kaby76/Antlr4BuildTasks#6]
When trying to build a project I get an error `The "SubtractList" task failed unexpectedly.`
This seems to be an issue with the msbuild task Antlr4.

```
1>C:\Users\emphasis\.nuget\packages\antlr4buildtasks\8.2.0\build\Antlr4BuildTasks.targets(262,3): error MSB4018: The "SubtractList" task failed unexpectedly.
1>C:\Users\emphasis\.nuget\packages\antlr4buildtasks\8.2.0\build\Antlr4BuildTasks.targets(262,3): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Users\emphasis\.nuget\packages\antlr4buildtasks\8.2.0\build\Antlr4BuildTasks.targets(262,3): error MSB4018:    at Antlr4.Build.Tasks.SubtractList.Execute()
1>C:\Users\emphasis\.nuget\packages\antlr4buildtasks\8.2.0\build\Antlr4BuildTasks.targets(262,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\emphasis\.nuget\packages\antlr4buildtasks\8.2.0\build\Antlr4BuildTasks.targets(262,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Antlr4 Include="Fluent.g4">
      <Visitor>true</Visitor>
      <Listener>false</Listener>
    </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.8.0" />
    <PackageReference Include="Antlr4BuildTasks" Version="8.2.0" />
  </ItemGroup>

</Project>
```

Fluent.g4
```
grammar Fluent;

/*
 * Parser Rules
 */

chat                : line line EOF ;
line                : name SAYS opinion NEWLINE;
name                : WORD ;
opinion             : TEXT ;

/*
 * Lexer Rules
 */

fragment A          : ('A'|'a') ;
fragment S          : ('S'|'s') ;
fragment Y          : ('Y'|'y') ;
fragment LOWERCASE  : [a-z] ;
fragment UPPERCASE  : [A-Z] ;

SAYS                : S A Y S ;
WORD                : (LOWERCASE | UPPERCASE)+ ;
TEXT                : '"' .*? '"' ;
WHITESPACE          : (' '|'\t')+ -> skip ;
NEWLINE             : ('\r'? '\n' | '\r')+ ;
```

**Comment by kaby76** [comment]
I updated the code to be more robust in the face of null pointers in SubtractList and MakeRelativeList. What happens here is that the Antlr Java tool outputs a list of files that it has generated. That list has to be cleaned up for MSBuild so it can compile those generated files. Unfortunately, MS's build rules for C# are rather picky: file names cannot be duplicated, otherwise one gets duplicate symbol definition errors in IDEs, builds. Please give the new package version a try by updating your .csproj file to 8.3 for Antlr4BuildTasks, and let me know how it goes. If this doesn't work, try to send me a diagnostic build trace,  dotnet build --verbosity diagnostic. --Ken

**Comment by emphasis87** [comment]
Seems to work fine, thanks for the timely fix. Coincidentally, how do you debug the MSBuild task? If you have a prepared setup, could you please add it to this repository?

**Comment by kaby76** [comment]
Yes, debugging a build is tricky. What I do is place a Sleep() call somewhere in the code, start the build, then do an attach to msbuild.exe that I guess is the right one, and set the breakpoint to somewhere. It's a real headache because there are processes spawning processes.

**Comment by emphasis87** [comment]
I see. I will give it a try sometime. I think you can close the issue for now.
