### ISSUE TITLE
Building first project - help needed

### ISSUE THREAD

**Issue by swidz** [kaby76/Antlr4BuildTasks#8]
Hi,

I am just starting with Antlr4 and trying to compile my first project. 
Not sure how should I organize the solution and what is the exact procedure for generating parser code
Perhaps you could provide some guildlines. I have done the following

1. I am using Visual Studio 2019 Professional (latest version 16.7.3)

2. I have installed VS extension AntlrVSIX 8.0 (using the Extension Manager)

3. In my solution I have created a .NET Standard 2.1 Library project

4. Created a dummy .cs class 

5. I have referenced the following packages using NuGet
a. Antlr4.Runtime.Standard Version 4.8
b. Antlr4BuildTasks Version 8.3.0

6. I have added grammar files, TSqlParser.g4 and TSqlLexer.g4 found here (I am trying to create a TSQL Parser)
https://github.com/antlr/grammars-v4/tree/master/sql/tsql

7. My .csproj project file looks as follows:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>   
  
  <ItemGroup>
    <Antlr4 Include="TSqlLexer.g4">
      <Package>MyLib.SQLParser</Package>
      <Visitor>false</Visitor>
      <Error>false</Error>
      <Listener>false</Listener>      
    </Antlr4>
    <Antlr4 Include="TSqlParser.g4">
      <Package>MyLib.SQLParser</Package>
      <Visitor>false</Visitor>
      <Error>false</Error>
      <Listener>false</Listener>      
    </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.8.0" />
    <PackageReference Include="Antlr4BuildTasks" Version="8.3.0" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>3021;1701;1702</NoWarn>
  </PropertyGroup>

</Project>
```

8. Files TSqlParser.cs and TSqlLexer.cs get created in the folder
\MyLib.SQLParser\bin\Debug\netstandard2.1

My questions are as follows:

- How should be the solution organized?
- Should I create a separate project (referencing Antlr4BuildTasks and Antlr4.Runtime.Standard) only with grammar files that after rebuild would create .cs files
- Should I copy these files later on to my other project (or reference them by adding existing items from ...bin\Debug\netstandard2.1 folder)
or maybe it all should be a part of a single library project (the library will also include other classes, functionality, etc. ?

**Comment by kaby76** [comment]
These are basically questions on how you want to organize your C# program. You can place the grammar files in its own project or within a project that has a wrapper around the Antlr code. The deciding factor is whether you want to expose the Antlr parse tree produced from a parse, expose some wrapper of it, or don't expose anything about the parse whatsoever. Whatever you decide, you don't want to get in the habit of copying the generated files around, or checking them into a version control system because you might get a version screw if you update the runtime without regenerating the .cs files.

**Comment by swidz** [comment]
Hi Ken, 
Thanks for the answer. 

I have noticed that there is an **AntOutDir** attribute which specifies what is the output directory. 
Perhaps you could add it on the readme page along with other listed attributes.

So my final solution is two separate projects A (MyLib.SqlParser.Grammar) and B (MyLib.SqlParser),
A is only for grammar files, the output (set using the AntOutDir) points using the relative path to the folder where project B source files are
B build is depended on A
For .Net Standard projects Visual studio 2019 automatically shows all new files from the project folder and includes them in the build 

Project file for A (MyLib.SqlParser.Grammar) includes the following

<ItemGroup>    
    <Antlr4 Include="TSqlLexer.g4">
      <Package>MyLib.SqlParser</Package>
      <Visitor>true</Visitor>
      <Error>false</Error>
      <Listener>true</Listener>
      <AntOutDir>..\MyLib.SqlParser</AntOutDir>
    </Antlr4>
    <Antlr4 Include="TSqlParser.g4">
      <Package>MyLib.SqlParser</Package>
      <Visitor>true</Visitor>
      <Error>false</Error>
      <Listener>true</Listener>
      <AntOutDir>..\MyLib.SqlParser</AntOutDir>
    </Antlr4>
  </ItemGroup>

**Comment by kaby76** [comment]
Yes, I'll update the doc on AntOutDir. You can set AntOutDir if you really want to store the generated files somewhere other than the default.  You can set it up like that--whatever works for you. --Ken
