### ISSUE TITLE
Wrong paths when building/publishing in docker.

### ISSUE THREAD

**Issue by MJLHThomassenHadrian** [kaby76/Antlr4BuildTasks#84]
I have a dotnet project using Antlr4BuildTasks.

When i run the build in docker however, running `RUN dotnet publish "./ProjectFolder/MyProject.csproj" --no-restore -c Release`
I get the following errors:

```
40.90 CSC : error CS2001: Source file '/ProjectFolder/C:/Users/<myuser>/Documents/SomeFolder/src/ProjectFolder/obj/Release/net8.0/MyParser.cs' could not be found. [/ProjectFolder/MyProject.csproj]

```

These errors pop up for all files that should be generated, e.g. MyParser.cs, MyLexer.cs, MyParserBaseVistitor.cs etc.

It looks like the path `'/ProjectFolder/C:/Users/<myuser>/Documents...` is wrong, its appending a relative path and an absolute (windows) path.

Running dotnet publish on my own machine (so not when using `docker build` but just in the root of my project) does not show this issue.

**Comment by kaby76** [comment]
Please provide:
* Your .csproj.
* Output from `dotnet publish "./ProjectFolder/MyProject.csproj" --no-restore -c Release -v diag`.

**Comment by MJLHThomassenHadrian** [comment]
My csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <Antlr4 Include="MyLexer.g4">
        <Listener>false</Listener>
        <Visitor>true</Visitor>
        <Package>MyNamespace</Package>
      </Antlr4>
      <Antlr4 Include="MyParser.g4">
        <Listener>false</Listener>
        <Visitor>true</Visitor>
        <Package>MyNamespace</Package>
      </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.8.0" PrivateAssets="all" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="8.1.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SomeOtherProject.csproj" />
  </ItemGroup>

</Project>
```

`dotnet publish` output:

[builder.log](https://github.com/user-attachments/files/16260883/builder.log)

I've 'redacted' some sensitive names as this is a project for my company, but the setup is identical to what we have.

What i noticed is that, even though this is executed inside a docker container, on line 2646 you see:

```
Task "ReadLinesFromFile" (TaskId:2)
#10 1.814                      Task Parameter:File=obj/Release/net8.0/MyProject.csproj.AntlrToCompileList.txt (TaskId:2)
#10 1.819                      Output Item(s): 
#10 1.819                          ToCompileFiles=
#10 1.819                              C:/Users/<myuser>/Documents/ProjectFolder/MyProject/obj/Release/net8.0/MyLexer.cs
#10 1.819                              C:/Users/<myuser>/Documents/ProjectFolder/MyProject/obj/Release/net8.0/MyParser.cs
#10 1.819                              C:/Users/<myuser>/Documents/ProjectFolder/MyProject/obj/Release/net8.0/MyParserBaseListener.cs
#10 1.819                              C:/Users/<myuser>/Documents/ProjectFolder/MyProject/obj/Release/net8.0/MyParserBaseVisitor.cs
#10 1.819                              C:/Users/<myuser>/Documents/ProjectFolder/MyProject/obj/Release/net8.0/MyParserListener.cs
#10 1.819                              C:/Users/<myuser>/Documents/ProjectFolder/MyProject/obj/Release/net8.0/MyParserVisitor.cs (TaskId:2)
```

Which is wierd, i would expect the paths there to be the paths in the docker container, not my local hard drive. This repeats further on in the logs.

For reference, the dockerfile looks like this:

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /

COPY ./ ./

RUN dotnet restore
RUN dotnet publish "./MyProject/MyProject.csproj" --no-restore -c Release -v diag
```

**Comment by MJLHThomassenHadrian** [comment]
Ok, i found the issue, it is a user error, sorry for bothering you (although your suggestion of printing diagnostic info did help me trace down the issue).

The problem was that both on our build agent AND locally, i already ran `dotnet build -c Release` before triggering the docker file. The Docker file's COPY step copies all files into the docker container, including the build files. When docker build runs, it takes the `MyProject.csproj.AntlrToCompileList.txt` file from the obj/Release/net8.0 directory instead of generating a new one. `dotnet clean` did not clean this directory, so the build inside docker just took the cached files, which have the wrong paths (paths from build outside docker).

Just deleting the obj folder and then running the docker build fixed the issue.
